server:
  port: 7172

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: validate
      dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
