server:
  port: 7172

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:cashflow_db
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
