version: '3'
services:
  accounts-payable:
    image: andreygfranca/cash-flow
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb/cash_flow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mariadb
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect
    ports:
      - "7171:7171"
    networks:
      - mariadb

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-service
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "mariadb"
      MYSQL_USER: "mariadb"
      MYSQL_PASSWORD: "mariadb"
      MYSQL_DATABASE: "cash_flow"
    ports:
      - 3306:3306
    networks:
      - mariadb

networks:
  mariadb:
    driver: bridge
